[monitor:///var/log/auth.log]
disabled = false
index = os_security
sourcetype = linux_secure
followTail = 0

[monitor:///var/log/secure]
disabled = false
index = os_security
sourcetype = linux_secure
followTail = 0

[monitor:///opt/sample_data/auth.log]
disabled = false
index = os_security
sourcetype = linux_secure
